### ISSUE TITLE
Create repository 2023-ISP-MoodAndGrasp

### ISSUE THREAD

**Issue by CSAllenISD** [CSAllenISD/2023-ISP-MoodAndGrasp#1]
Created repository https://github.com/CSAllenISD/2023-ISP-MoodAndGrasp

**Comment by chizzyx** [comment]
There are five roles required on all teams: Development Engineer, QA Engineer, Project Manager, Product Manager, and Release Engineer.
The Development Engineer will be the person who designs the product. They will also be tasked with the main chunk of code although everyone will participate in some aspect of coding this project. 
The QA (quality assurance) Engineer will create tests to run the project through to make sure that project is up to code (pun). They will then report the issues back to the group so we can work together to fix them. 
The project manager is responible for planning, organizing, and overseeing the work of the team to achieve specific goals and meet project objectives. They will be tasked with keeping us on schedule as well as contributing to other aspects of the project. The Product Manager is responsible for gathering and analyzing market and customer data. They will work with the rest of this group to make the product easy to use. 
The Release Engineer will be responsible for building, testing, and deploying software releases. They work closely with Development Engineer and QA Engineer to ensure that the code is properly integrated and tested, and that it can be easily deployed to production environments. 
When we assigned these roles within the group we tried to work with our strengths and weaknesses. Will has the most history with coding so we decided that he would be the Development Engineer. Robel is really good at finding errors within code and often helps us find errors in our own code so he was chosen as the QA engineer. Because we only have four people and there are five roles somebody will have to take on two roles. I volunteered to be both the release engineer and project manager because the role of Release Engineer is mainly comprised of uploading versions to github and I will be able to handle both roles. Azmer volunteered to be the Product Manager because he is good at comprising schedules.
